backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "/src/static/img"
public_folder: "/img"

site_url: "https://surveymethodsroom.hu"

collections:
  - name: "hirek_hu"
    label: "Hírek"
    folder: "src/hu/hirek"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Cím", name: "title", widget: "string" }
      - { label: "Dátum", name: "date", widget: "datetime" }
      - { label: "Azonosító", name: "ref", widget: "string" }
      - { label: "Szöveg", name: "body", widget: "markdown" }
  - name: "proj_hu"
    label: "Projektek"
    folder: "src/hu/projektek"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Cím"
        name: "title"
        widget: "string"
      - label: "Dátum"
        name: "date"
        widget: "datetime"
      - label: "Azonosító"
        name: "ref"
        widget: "string"
      - label: "Alcím"
        name: "subtitle"
        widget: "string"
        required: false
      - label: "Szöveg"
        name: "body"
        widget: "markdown"
      - label: "További kutatók"
        name: "kutatok"
        widget: "list"
        required: false
        fields:
          - { label: "Kép", name: "img", widget: "image", required: false }
          - { label: "Név", name: "nev", widget: "string" }
          - {
              label: "Rövid leírás",
              name: "leiras",
              widget: "string",
              required: false,
            }
      - label: "Lábjegyzetbe képek (cellák)"
        name: "cellak"
        widget: "list"
        required: false
        fields:
          - { label: "Kép", name: "img", widget: "image", required: false }
  - name: "kutatok_hu"
    label: "Kutatók"
    folder: "src/hu/kutatok"
    create: true
    slug: "{{name}}"
    fields:
      - { label: "Név", name: "name", widget: "string", required: false }
      - {
          label: "Pozíció",
          name: "pos",
          widget: "string",
          hint: "Rövid leírás, alcímként jelenik meg a kutatócsoport-oldalon",
          required: false,
        }
      - {
          label: "Azonosító",
          name: "ref",
          widget: "string",
          hint: "Angol-magyar verzió váltáshoz",
        }
      - {
          label: "Bemutatkozás",
          name: "body",
          widget: "markdown",
          required: false,
        }
      - { label: "Kép", name: "img", widget: "image", required: false }
      - { label: "Sorrend", name: "order", widget: "number", required: false }
      - label: "Piktogrammok"
        name: "pikto"
        widget: "list"
        required: false
        field: { label: "Kép", name: "img", widget: "image", required: false }
      - label: "Logók kezdőoldalra"
        name: "logos"
        widget: "list"
        required: false
        fields:
          - { label: "Kép", name: "img", widget: "image", required: false }
  - name: "hirek_en"
    label: "Hírek (angol)"
    folder: "src/en/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Cím", name: "title", widget: "string" }
      - { label: "Dátum", name: "date", widget: "datetime" }
      - { label: "Azonosító", name: "ref", widget: "string" }
      - { label: "Szöveg", name: "body", widget: "markdown" }
  - name: "proj_en"
    label: "Projektek (angol)"
    folder: "src/en/projects"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Cím"
        name: "title"
        widget: "string"
      - label: "Dátum"
        name: "date"
        widget: "datetime"
      - label: "Azonosító"
        name: "ref"
        widget: "string"
      - label: "Alcím"
        name: "subtitle"
        widget: "string"
        required: false
      - label: "Szöveg"
        name: "body"
        widget: "markdown"
      - label: "További kutatók"
        name: "kutatok"
        widget: "list"
        required: false
        fields:
          - { label: "Kép", name: "img", widget: "image", required: false }
          - { label: "Név", name: "nev", widget: "string" }
          - {
              label: "Rövid leírás",
              name: "leiras",
              widget: "string",
              required: false,
            }
      - label: "Lábjegyzetbe képek (cellák)"
        name: "cellak"
        widget: "list"
        required: false
        fields:
          - { label: "Kép", name: "img", widget: "image", required: false }
  - name: "kutatok_en"
    label: "Kutatók (angol)"
    folder: "src/en/researchers"
    create: true
    slug: "{{name}}"
    fields:
      - { label: "Név", name: "name", widget: "string", required: false }
      - {
          label: "Pozíció",
          name: "pos",
          widget: "string",
          hint: "Rövid leírás, alcímként jelenik meg a kutatócsoport-oldalon",
          required: false,
        }
      - {
          label: "Azonosító",
          name: "ref",
          widget: "string",
          hint: "Angol-magyar verzió váltáshoz",
        }
      - {
          label: "Bemutatkozás",
          name: "body",
          widget: "markdown",
          required: false,
        }
      - { label: "Kép", name: "img", widget: "image", required: false }
      - { label: "Sorrend", name: "order", widget: "number", required: false }
      - label: "Piktogrammok"
        name: "pikto"
        widget: "list"
        required: false
        field: { label: "Kép", name: "img", widget: "image", required: false }
  - name: "intern_hu"
    label: "Gyakornokok (magyar)"
    folder: "src/hu/gyakornokok"
    create: true
    slug: "{{name}}"
    fields:
      - { label: "Név", name: "name", widget: "string" }
      - {
          label: "Rövid leírás / pozíció",
          name: "description",
          widget: "string",
          required: false,
        }
      - { label: "Kép", name: "img", widget: "image" }
      - label: "Piktogrammok"
        name: "pikto"
        widget: "list"
        required: false
        field: { label: "Kép", name: "img", widget: "image", required: false }
  - name: "intern_en"
    label: "Gyakornokok (angol)"
    folder: "src/en/intern"
    create: true
    slug: "{{name}}"
    fields:
      - { label: "Név", name: "name", widget: "string" }
      - {
          label: "Rövid leírás / pozíció",
          name: "description",
          widget: "string",
          required: false,
        }
      - { label: "Kép", name: "img", widget: "image" }
      - label: "Piktogrammok"
        name: "pikto"
        widget: "list"
        required: false
        field: { label: "Kép", name: "img", widget: "image", required: false }
  - name: "junior_hu"
    label: "Junior kutatók (magyar)"
    folder: "src/hu/junior"
    create: true
    slug: "{{name}}"
    fields:
      - { label: "Név", name: "name", widget: "string" }
      - {
          label: "Rövid leírás / pozíció",
          name: "description",
          widget: "string",
          required: false,
        }
      - { label: "Kép", name: "img", widget: "image" }
      - label: "Piktogrammok"
        name: "pikto"
        widget: "list"
        required: false
        field: { label: "Kép", name: "img", widget: "image", required: false }
  - name: "junior_en"
    label: "Junior kutatók (angol)"
    folder: "src/en/junior"
    create: true
    slug: "{{name}}"
    fields:
      - { label: "Név", name: "name", widget: "string" }
      - {
          label: "Rövid leírás / pozíció",
          name: "description",
          widget: "string",
          required: false,
        }
      - { label: "Kép", name: "img", widget: "image" }
      - label: "Piktogrammok"
        name: "pikto"
        widget: "list"
        required: false
        field: { label: "Kép", name: "img", widget: "image", required: false }
  - name: "earlier_contributors_hu"
    label: "Korábbi résztvevő kutatók (magyar)"
    folder: "src/hu/earlier_contributors"
    create: true
    slug: "{{name}}"
    fields:
      - { label: "Név", name: "name", widget: "string" }
      - {
          label: "Rövid leírás / pozíció",
          name: "description",
          widget: "string",
          required: false,
        }
      - { label: "Kép", name: "img", widget: "image" }
      - label: "Piktogrammok"
        name: "pikto"
        widget: "list"
        required: false
        field: { label: "Kép", name: "img", widget: "image", required: false }
  - name: "earlier_contributors_en"
    label: "Korábbi résztvevő kutatók (angol)"
    folder: "src/en/earlier_contributors"
    create: true
    slug: "{{name}}"
    fields:
      - { label: "Név", name: "name", widget: "string" }
      - {
          label: "Rövid leírás / pozíció",
          name: "description",
          widget: "string",
          required: false,
        }
      - { label: "Kép", name: "img", widget: "image" }
      - label: "Piktogrammok"
        name: "pikto"
        widget: "list"
        required: false
        field: { label: "Kép", name: "img", widget: "image", required: false }
  - name: "home_hu"
    label: "Kezdőoldal (magyar)"
    folder: "src/hu"
    create: true
    fields:
      - { label: Leírás, name: body, widget: markdown }
  - name: "home_en"
    label: "Kezdőoldal (angol)"
    folder: "src/en"
    create: true
    fields:
      - { label: Leírás, name: body, widget: markdown }
